version: '2'

services: 
    webserver:
        container_name: archpkgcompare_webserver
        image: arch_pkg_compare_webserver
        volumes:
            - ./data/packageStatistics.json:/root/server/packageStatistics.json
            - ./data/ArchPackageCompareStats/templates:/root/server/templates/
        networks:
          - archpkgcompare_webserver_default
networks:
    archpkgcompare_webserver_default:
      external: true
